"""
graph_mcp — a custom MCP server wrapping Neo4j routing queries over the
Chennai Metro graph.

Tools exposed:
  - get_route : find the shortest path between two stations, returned
    as structured ride segments (line, board station, alight station,
    direction-towards-terminal, stop count) — NOT a pre-phrased
    sentence. The calling agent's LLM turns this structured data into
    natural language, the way a metro announcement would phrase it
    ("Take the Blue Line towards Wimco Nagar Depot, get down at
    Chennai Central, then take the Green Line towards St. Thomas
    Mount, get down at Egmore").

This keeps the deterministic/LLM split exactly where the rest of the
project puts it: Neo4j computes the real path and the real direction
facts; the LLM only phrases what's already been computed. No station
order, line name, or direction is ever generated by the LLM.

Run standalone for local testing:
    python -m mcp_servers.graph_mcp.server

Run via the MCP Inspector:
    npx @modelcontextprotocol/inspector python -m mcp_servers.graph_mcp.server
"""

from __future__ import annotations

import json

from pydantic import BaseModel, ConfigDict, Field

from mcp.server.fastmcp import FastMCP

from mcp_servers.graph_mcp.neo4j_client_wrapper import (
    Neo4jUnreachableError,
    get_route,
    list_all_station_names,
)

mcp = FastMCP("graph_mcp")


def _unreachable_response(exc: Neo4jUnreachableError) -> str:
    return json.dumps({"error": str(exc)}, indent=2)


class GetRouteInput(BaseModel):
    """Input model for a station-to-station routing query."""

    model_config = ConfigDict(str_strip_whitespace=True, extra="forbid")

    source_station: str = Field(
        ...,
        description=(
            "Exact name of the station the journey starts from, e.g. "
            "'Teynampet'. Must match an actual Chennai Metro station "
            "name — resolve colloquial names or typos to the canonical "
            "station name before calling this tool."
        ),
        min_length=1,
        max_length=100,
    )
    destination_station: str = Field(
        ...,
        description=(
            "Exact name of the destination station, e.g. 'Egmore'. "
            "Same naming requirement as source_station."
        ),
        min_length=1,
        max_length=100,
    )


@mcp.tool(
    name="get_route",
    annotations={
        "title": "Get Metro Route Between Two Stations",
        "readOnlyHint": True,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": False,
    },
)
async def get_route_tool(params: GetRouteInput) -> str:
    """Find the fastest route between two Chennai Metro stations,
    including any line changes required.

    Use this whenever the user asks how to get from one station to
    another, or which line(s)/direction to take. This tool returns
    STRUCTURED route segments, not a finished sentence — phrase the
    result the way a real metro announcement would: name the line,
    the terminal station in the direction of travel ("towards X"),
    and where to get off / change lines, using EXACTLY the station
    and line names given in the response. Do not rename, abbreviate,
    or invent any station/line name not present in the tool output.

    Args:
        params (GetRouteInput): Contains:
            - source_station (str): exact starting station name.
            - destination_station (str): exact destination station name.

    Returns:
        str: JSON object. On success:
            {
              "found": true,
              "segments": [
                {
                  "line": "Blue",
                  "board_station": "Teynampet",
                  "alight_station": "Chennai Central",
                  "direction_towards": "Wimco Nagar Depot",
                  "stop_count": 5
                },
                {
                  "line": "Green",
                  "board_station": "Chennai Central",
                  "alight_station": "Egmore",
                  "direction_towards": "St. Thomas Mount",
                  "stop_count": 1
                }
              ],
              "transfer_count": 1,
              "total_stops": 6
            }
        Each segment is one continuous ride on one line. Consecutive
        segments imply a transfer at the shared station (segment N's
        alight_station == segment N+1's board_station).
        If either station name is unrecognized:
            {"error": "...", "available_stations": [...]}
        If Neo4j is unreachable:
            {"error": "Could not reach Neo4j: <details>"}
        If no path exists between two otherwise-valid stations:
            {"found": false, "segments": [], "transfer_count": 0, "total_stops": 0}
    """
    try:
        known_stations = list_all_station_names()
    except Neo4jUnreachableError as exc:
        return _unreachable_response(exc)

    unknown = [
        s for s in (params.source_station, params.destination_station)
        if s not in known_stations
    ]
    if unknown:
        return json.dumps(
            {
                "error": (
                    f"Station name(s) not recognized: {unknown}. "
                    f"Station names must match exactly."
                ),
                "available_stations": known_stations,
            },
            indent=2,
        )

    try:
        result = get_route(params.source_station, params.destination_station)
    except Neo4jUnreachableError as exc:
        return _unreachable_response(exc)

    return json.dumps(result, indent=2)


if __name__ == "__main__":
    mcp.run()
